import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const inter = Inter({ subsets: ["latin"] });

const nohemi = localFont({
  src: [
    {
      path: '../public/fonts/Nohemi-Regular.woff',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/Nohemi-Thin.woff',
      weight: '100',
      style: 'normal',
    }
  ],
  variable: "--font-nohemi"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nohemi.className}`}>{children}</body>
    </html>
  );
}
